flags:
  ohua-core:
    debug: true
extra-package-dbs: []
packages:
- ./core
- ./test-tools
- ./tests

extra-deps: 
  - git: https://github.com/ohua-dev/alang-ml-parser
    commit:  55afe8e5de0417f6be00ff87586a8436c94529c1

resolver: lts-12.6
