flags: {}
extra-package-dbs: []
packages:
- ./core
- ./test-tools
- ./tests
- location:
    git: https://github.com/ohua-dev/alang-ml-parser
    commit: 17ad1606549984ddd68bc6a0a2d0d074ae9b8be5
  extra-dep: true
extra-deps: []
resolver: lts-12.6
